services:
  gcv:
    build:
      context: gcv
      target: dev
    ports:
      - "${GCV_PORT:-4200}:4200"
    volumes:
      - ./gcv:/gcv
      - /gcv/dep
      - /gcv/scripts
      - /gcv/node_modules

  reverse-proxy:
    ports:
      - "${TRAEFIK_API_PORT:-8080}:8080"
    environment:
      - TRAEFIK_LOG_LEVEL=${TRAEFIK_LOG_LEVEL:-DEBUG}
      - TRAEFIK_API_INSECURE=true

  envoy:
    environment:
      loglevel: debug

  chromosome:
    build: microservices/chromosome

  chromosome_search:
    build: microservices/chromosome_search

  chromosome_region:
    build: microservices/chromosome_region

  genes:
    build: microservices/genes

  gene_search:
    build: microservices/gene_search

  macro_synteny_blocks:
    build: microservices/macro_synteny_blocks

  micro_synteny_search:
    build: microservices/micro_synteny_search

  pairwise_macro_synteny_blocks:
    build: microservices/pairwise_macro_synteny_blocks

  search:
    build: microservices/search

  redis_loader:
    build: microservices/redis_loader
    volumes:
      - ./data/test/:/data

  chado:
    image: postgres
    environment:
      POSTGRES_PASSWORD: gcv
    ports:
      - 5432:5432
    volumes:
    - ./data/postgresql:/var/lib/postgresql/data
    - ./data/chado_dumps:/dumps
    profiles: [chado]
