services:
  gcv:
    image: ghcr.io/legumeinfo/gcv:2.6.0
    ports:
      - "${GCV_PORT:-80}:80"
    environment:
      - GCV_PATH=${GCV_PATH:-/gcv}
    volumes:
      - ./config:/usr/share/nginx/html/config
    restart: always

  reverse-proxy:
    environment:
      - TRAEFIK_LOG_LEVEL=${TRAEFIK_LOG_LEVEL:-ERROR}
      - TRAEFIK_API_INSECURE=false
      - TRAEFIK_PROVIDERS_DOCKER_CONSTRAINTS=Label(`traefik.zone`,`${COMPOSE_PROJECT_NAME}`)
    labels:
      - "traefik.zone=${COMPOSE_PROJECT_NAME}"

  envoy:
    environment:
      loglevel: error
    labels:
      - "traefik.zone=${COMPOSE_PROJECT_NAME}"

  chromosome:
    image: ghcr.io/legumeinfo/microservices-chromosome:1.1.3
    labels:
      - "traefik.zone=${COMPOSE_PROJECT_NAME}"

  chromosome_search:
    image: ghcr.io/legumeinfo/microservices-chromosome_search:1.1.3

  chromosome_region:
    image: ghcr.io/legumeinfo/microservices-chromosome_region:1.1.3
    labels:
      - "traefik.zone=${COMPOSE_PROJECT_NAME}"

  genes:
    image: ghcr.io/legumeinfo/microservices-genes:1.1.3
    labels:
      - "traefik.zone=${COMPOSE_PROJECT_NAME}"

  gene_search:
    image: ghcr.io/legumeinfo/microservices-gene_search:1.1.3

  macro_synteny_blocks:
    image: ghcr.io/legumeinfo/microservices-macro_synteny_blocks:1.3.3
    labels:
      - "traefik.zone=${COMPOSE_PROJECT_NAME}"

  macro_synteny_paf:
    image: ghcr.io/legumeinfo/microservices-macro_synteny_paf:1.3.3
    labels:
      - "traefik.zone=${COMPOSE_PROJECT_NAME}"

  micro_synteny_search:
    image: ghcr.io/legumeinfo/microservices-micro_synteny_search:1.1.3
    labels:
      - "traefik.zone=${COMPOSE_PROJECT_NAME}"

  pairwise_macro_synteny_blocks:
    image: ghcr.io/legumeinfo/microservices-pairwise_macro_synteny_blocks:1.3.3

  search:
    image: ghcr.io/legumeinfo/microservices-search:1.1.3
    labels:
      - "traefik.zone=${COMPOSE_PROJECT_NAME}"

  redis_loader:
    image: ghcr.io/legumeinfo/microservices-redis_loader:1.3.0
