services:
  gcv:
    build:
      context: gcv
      target: dev
    ports:
      - "${GCV_PORT:-4200}:4200"
    volumes:
      - ./gcv:/gcv
      - /gcv/dep
      - /gcv/scripts
      - /gcv/node_modules

  reverse-proxy:
    ports:
      - "${TRAEFIK_API_PORT:-8080}:8080"
    environment:
      - TRAEFIK_LOG_LEVEL=${TRAEFIK_LOG_LEVEL:-DEBUG}
      - TRAEFIK_API_INSECURE=true

  envoy:
    environment:
      loglevel: debug

  chromosome:
    build: microservices/chromosome
    environment:
      - LOG_LEVEL=DEBUG

  chromosome_search:
    build: microservices/chromosome_search
    environment:
      - LOG_LEVEL=DEBUG

  chromosome_region:
    build: microservices/chromosome_region
    environment:
      - LOG_LEVEL=DEBUG

  genes:
    build: microservices/genes
    environment:
      - LOG_LEVEL=DEBUG

  gene_search:
    build: microservices/gene_search
    environment:
      - LOG_LEVEL=DEBUG

  macro_synteny_blocks:
    build: microservices/macro_synteny_blocks
    environment:
      - LOG_LEVEL=DEBUG

  macro_synteny_paf:
    build: microservices/macro_synteny_paf
    environment:
      - LOG_LEVEL=DEBUG

  micro_synteny_search:
    build: microservices/micro_synteny_search
    environment:
      - LOG_LEVEL=DEBUG

  pairwise_macro_synteny_blocks:
    build: microservices/pairwise_macro_synteny_blocks
    environment:
      - LOG_LEVEL=DEBUG

  search:
    build: microservices/search
    environment:
      - LOG_LEVEL=DEBUG

  redis_loader:
    build: microservices/redis_loader
    volumes:
      - ./data/test/:/data

  chado:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: gcv
    ports:
      - 5432:5432
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
    profiles: [chado]
